FROM python:3.12-slim

WORKDIR /app

# Accept build arguments
ARG HOME_DIR

# Set environment variables
ENV HOME_DIR=${HOME_DIR}

# Copy the requirements file and install dependencies
COPY requirements-chat-service.txt .
RUN pip3 install -r requirements-chat-service.txt

# Copy the .env file
COPY *.env ./

# Copy the rest of the application code
COPY . .

# Copy the entrypoint script
COPY entrypoint.sh /app/entrypoint.sh

# Ensure the entrypoint script has execute permissions
RUN chmod +x /app/entrypoint.sh

# Copy one file from ../pdf-data to /app/pdf-data
# COPY ${HOME_DIR}/pdf-data/3p-learning-2015-db.pdf /app/pdf-data/3p-learning-2015-db.pdf

# Expose the port the app runs on
EXPOSE 5001

# Use the shell script as the entry point
ENTRYPOINT ["/app/entrypoint.sh"]