FROM python:3.12.2-slim

WORKDIR /app

# Install curl and other dependencies
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Accept build arguments
ARG HOME_DIR

# Set environment variables
ENV HOME_DIR=${HOME_DIR}

# RUN pip3 install --upgrade pip
# Copy the requirements file and install dependencies
COPY requirements-chat-service.txt .
RUN pip3 install -r requirements-chat-service.txt

# Copy the .env file
COPY *.env ./

# Copy the rest of the application code
COPY . .

# Copy the entrypoint script
COPY entrypoint.sh /app/entrypoint.sh

# Ensure the entrypoint script has execute permissions
RUN chmod +x /app/entrypoint.sh

# Copy one file from ../pdf-data to /app/pdf-data
# COPY ${HOME_DIR}/pdf-data/3p-learning-2015-db.pdf /app/pdf-data/3p-learning-2015-db.pdf

# Port for chat service
EXPOSE 5001

# Port for source management service
EXPOSE 5003 

# Use the shell script as the entry point
ENTRYPOINT ["/app/entrypoint.sh"]