server:
  port: 8080

spring:
  application:
    name: spring-consul-service
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: stock-viewer-service
          uri: http://stock-viewer-service:6000
          predicates:
            - Path=/api/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway